services:
  # Backend Service (Python/FastAPI)
  - type: web
    name: backend
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  # Frontend Service (React/Vite Static Site)
  - type: static_site # <-- CORRECCIÓN: 'static' cambiado por 'static_site'
    name: frontend
    rootDir: "Technology Inclusion pagina"
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    # Add rewrite rules for client-side routing (for React Router)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html