services:
  # Backend Service (Python/FastAPI)
  - type: web
    name: backend
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  # Frontend Service (Static Site)
  - type: web
    name: frontend
    runtime: static
    rootDir: "Technology Inclusion pagina" # Directorio donde se ejecuta el buildCommand
    buildCommand: "npm install && npm run build"
    staticPublishPath: "Technology Inclusion pagina/dist" # Directorio a servir, relativo a la raíz del repo
    routes:
      - type: rewrite
        source: /*
        destination: /index.html