services:
  # Backend (FastAPI) en plan FREE
  - type: web
    name: backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /api/health

  # Frontend (Vite) como sitio estático (gratis)
  - type: web
    name: frontend
    runtime: static
    rootDir: "Technology Inclusion pagina"
    buildCommand: "bun install && bun run build" # <-- CORRECCIÓN: Usando bun en lugar de npm
    staticPublishPath: "./Technology Inclusion pagina/dist"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html